title: Ethics Frameworks [WIP]
logo: /assets/img/logo.png
description: Frameworks for balanced teams considering the outcomes of the products they create
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
